# Site settings
title: CodeCook
email: codecook@tangsj.com
description: > # codecook site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tangsj.com" # the base hostname & protocol for your site
github_username:  tangsj

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty