timezone: Asia/ChongQing

# Site settings
title: CodeCook
email: t_fate@163.com
description: > # codecook site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tangsj.com" # the base hostname & protocol for your site
github_username:  tangsj
keep_record: "渝ICP备14005794号"

port: 4000

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
permalink: pretty