# Site settings
title: CodeCook
email: t_fate@163.com
description: > # codecook site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tangsj.com" # the base hostname & protocol for your site
github_username:  tangsj

# Build settings
highlighter: pygments
markdown: redcarpet
permalink: pretty 